version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'actions'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    rebase-strategy: 'auto'
    labels:
      - 'security'
      - 'dependencies'
