name: Dependabot Automerge

on: pull_request

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
        - name: Automerge Dependabot PR 🤖
          uses: actions/github-script@v3
          with:
            script: |
              github.pulls.createReview({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE'
              })
              github.pulls.merge({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payloasd.pull_request.number,
                merge_method: 'squash'
              })