name: Merge Pull Requests

on:
  workflow_run:
    workflows: ["Automated Checks"]
    types: [completed]

jobs:
  merge:
    name: Automated Merge
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    steps:
        - name: Automerge Dependabot PR 🤖
          uses: actions/github-script@v3
          with:
            script: |
              github.pulls.createReview({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE'
              })
              github.pulls.merge({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash'
              })